language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
services:
  - mysql
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev python-lxml
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-fr
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - export DJANGO_SETTINGS_MODULE=semences05.settings.unittest
  - export PYTHONDONTWRITEBYTECODE=yes
  - python manage.py compress
  - python manage.py collectstatic
script: python manage.py test
