language: python
python:
  - "2.7"

env:
  - DJANGO=1.9.2

services:
  - mysql

before_install:
  - export DJANGO_SETTINGS_MODULE=semences05.settings.unittest
  - export PYTHONPATH=$HOME/builds/SwanMougnoz/semences05
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev python-lxml
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-fr
  - python manage.py collectstatic
  - python manage.py compress

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script: python manage.py test
