# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-27 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variete',
            name='photo',
            field=models.ImageField(upload_to=b's5appadherant/images/varietes/'),
        ),
    ]
