# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-15 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import s5appadherant.models.variete


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0005_auto_20161206_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variete',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=s5appadherant.models.variete.get_variete_upload_path),
        ),
    ]
