# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-17 08:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s5appadherant', '0006_auto_20161215_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=10, null=True)),
                ('est_professionnel', models.BooleanField(default=False)),
                ('experience', models.CharField(choices=[(b'debutant', b'D\xc3\xa9butant'), (b'confirme', b'Confirm\xc3\xa9')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Jardin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appelation', models.CharField(max_length=255)),
                ('exposition', models.IntegerField()),
                ('type_sol', models.CharField(max_length=255)),
                ('irrigation', models.CharField(max_length=255)),
                ('mise_en_culture', models.IntegerField()),
                ('description', models.TextField()),
                ('superficie', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='adherant',
            name='jardins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s5appadherant.Jardin'),
        ),
        migrations.AddField(
            model_name='adherant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
