# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-17 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0007_auto_20161217_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherant',
            name='jardins',
        ),
        migrations.AddField(
            model_name='jardin',
            name='proprietaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s5appadherant.Adherant'),
            preserve_default=False,
        ),
    ]
