# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-17 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0008_auto_20161217_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('altitude', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='adherant',
            name='adresse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s5appadherant.Adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jardin',
            name='adresse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s5appadherant.Adresse'),
            preserve_default=False,
        ),
    ]
