# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-20 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0009_auto_20161217_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conservation', models.CharField(choices=[(b'dynamique', b'Dynamique'), (b'conservatoire', b'Conservatoire')], max_length=255)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(null=True)),
                ('jardin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s5appadherant.Jardin')),
                ('variete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s5appadherant.Variete')),
            ],
        ),
    ]
