# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-30 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0010_culture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepte', models.BooleanField(default=False)),
                ('adherant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s5appadherant.Adherant')),
                ('jardin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s5appadherant.Jardin')),
            ],
        ),
    ]
