# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-08 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0011_entretient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entretient',
            new_name='Cultivateur',
        ),
    ]
