# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-22 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0012_auto_20170108_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jardin',
            name='exposition',
            field=models.CharField(max_length=255),
        ),
    ]
