# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-22 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0013_auto_20170122_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='variete',
            name='date_ajout',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 1, 22, 10, 34, 34, 416823, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='culture',
            name='date_debut',
            field=models.DateField(),
        ),
    ]
