# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-22 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0016_auto_20170122_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='jardin',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variete',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
