# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0002_remove_action_data'),
        ('s5appadherant', '0018_auto_20170122_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedAction',
            fields=[
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='processed', serialize=False, to='actstream.Action')),
            ],
        ),
    ]
