# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0019_processedaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivateur',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
