# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 16:34
from __future__ import unicode_literals

import time
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0021_auto_20170128_1634')
    ]

    # pour la compat sqlite :/
    now = time.strftime("%Y-%m-%d")

    operations = [
        migrations.RunSQL("DELETE FROM s5appadherant_cultivateur"),
        migrations.RunSQL("INSERT INTO actstream_follow(object_id, actor_only, started, content_type_id, user_id) "
                          "SELECT j.id, 0, '%s', ct.id, u.id "
                          "FROM s5appadherant_jardin AS j "
                          "  JOIN s5appadherant_adherant AS a ON a.id = j.proprietaire_id "
                          "  JOIN auth_user AS u ON u.id = a.user_id "
                          "  JOIN django_content_type AS ct ON ct.app_label = 's5appadherant' AND ct.model = 'jardin'" % now)
    ]
