# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-18 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s5appadherant', '0022_patch_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='altitude',
            field=models.IntegerField(null=True, verbose_name=b'Altitude (en m)'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='superficie',
            field=models.FloatField(verbose_name=b'Superficie (en m\xc2\xb2)'),
        ),
    ]
