# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s5vitrine', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewname', models.CharField(max_length=255)),
                ('params', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menuitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('lien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s5vitrine.Lien')),
            ],
        ),
        migrations.CreateModel(
            name='PageContenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_page', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('menuitem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='s5vitrine.Menuitem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lien',
            unique_together=set([('viewname', 'params')]),
        ),
    ]
