# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s5vitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menuitem',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PageContenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_page', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageGenerique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewname', models.CharField(max_length=255)),
                ('params', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='_page_contenu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='s5vitrine.PageContenu'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='_page_generique',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='s5vitrine.PageGenerique'),
        ),
    ]
