# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s5vitrine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='libelle',
            new_name='label',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='identifier',
            field=models.CharField(default='main', max_length=255),
            preserve_default=False,
        ),
    ]
