# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-15 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s5vitrine', '0002_auto_20161114_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='identifier',
            new_name='identifiant',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='label',
            new_name='libelle',
        ),
    ]
