# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-13 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s5vitrine', '0002_auto_20161112_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_page', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('lien_menu', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='s5vitrine.Menuitem')),
            ],
        ),
    ]
