# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-13 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s5vitrine', '0003_pagecontenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewname', models.CharField(max_length=255)),
                ('params', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='lien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s5vitrine.Lien'),
        ),
        migrations.AlterField(
            model_name='pagecontenu',
            name='lien_menu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='s5vitrine.Lien'),
        ),
        migrations.AlterUniqueTogether(
            name='lien',
            unique_together=set([('viewname', 'params')]),
        ),
    ]
