# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-15 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s5vitrine', '0003_auto_20161115_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='active',
            new_name='actif',
        ),
    ]
