"""
Django settings for semences05 project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import locale
import os

from semences05.settings.ckeditor import *

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
APP_DIR = os.path.join(PROJECT_DIR, 'semences05')
VITRINE_DIR = os.path.join(PROJECT_DIR, 's5vitrine')
APPADHERANT_DIR = os.path.join(PROJECT_DIR, 's5appadherant')
MAILING_DIR = os.path.join(PROJECT_DIR, 's5mailing')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_x$spukwy23bm%t)q!7vut010b+v43xgx*)eb)px-ci5k6+gzs'
DEBUG = False
ALLOWED_HOSTS = []

# Application definition

PREREQ_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'djangobower',
    'bootstrapform',
    'ckeditor',
    'ckeditor_uploader',
    'django_bootstrap_breadcrumbs',
    'widget_tweaks',
    'compressor',
    'table',
    'rules',
    'django_dynamic_fixture',
    'actstream',
    'mailviews',
    'maintenance_mode',
    'debug_toolbar',
    'rest_framework',
    'django_js_reverse'
]

PROJECT_APPS = [
    's5appadherant',
    's5vitrine',
    's5mailing',
    'semences05'
]

INSTALLED_APPS = PREREQ_APPS + PROJECT_APPS

MIDDLEWARE_CLASSES = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'maintenance_mode.middleware.MaintenanceModeMiddleware'
]

ROOT_URLCONF = 'semences05.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(VITRINE_DIR, 'templates'),
            os.path.join(APPADHERANT_DIR, 'templates'),
            os.path.join(MAILING_DIR, 'templates'),
            os.path.join(APP_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'semences05.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(PROJECT_DIR, 'var', 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = 's5appadherant:login'

# Authentication

AUTHENTICATION_BACKENDS = (
    'rules.permissions.ObjectPermissionBackend',
    'semences05.backends.UserModelEmailBackend'
)


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

locale.setlocale(locale.LC_TIME, "fr_FR.UTF-8")
LANGUAGE_CODE = 'fr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'frontend/sass/stylesheets'),
    os.path.join(PROJECT_DIR, 'var/assets')
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
    'compressor.finders.CompressorFinder'
]

BOWER_COMPONENTS_ROOT = os.path.join(PROJECT_DIR, 'frontend')

BOWER_INSTALLED_APPS = (
    'bootstrap-sass',
    'leaflet',
    'font-awesome',
    'datetimepicker',
    'handlebars'
)

MEDIA_ROOT = os.path.join(PROJECT_DIR, 'var/media')
MEDIA_URL = '/media/'

COMPRESS_ROOT = os.path.join(PROJECT_DIR, 'var/assets')

# Emails

DEFAULT_FROM_EMAIL = 'noreply@grainedesmontagnes.org'
SERVER_EMAIL = 'admin@grainedesmontagnes.org'
CONTACT_EMAIL = 'contact@grainedesmontagnes.org'

# Misc

DDF_DEFAULT_DATA_FIXTURE = 'random'

ACTSTREAM_SETTINGS = {
    'MANAGER': 's5appadherant.managers.action.S5ActionManager',
    'FETCH_RELATIONS': True,
    'USE_PREFETCH': True,
    'GFK_FETCH_DEPTH': 5,
}

JS_REVERSE_INCLUDE_ONLY_NAMESPACES = ['s5api', 's5vitrine', 's5appadherant']
